### ISSUE TITLE
Incorrect consolidation of ABI for events.

### ISSUE THREAD

**Issue by hickscorp** [projectsophon/hardhat-diamond-abi#16]
Consider that
- A diamond has two facets - `FacetA` and `FacetB`.
- Both rely on a library for storage and other things - eg `MyLib`.
- Both `FacetA` and `FacetB` need to emit `SomeEvent`.

At this point, there are different ways of doing things:
1. Declare the events in `MyLib` - it is valid Solidity - and from `FacetA` (or `FacetB`) one could call `emit MyLib.SomeEvent(...)`.
2. Declare the events in `FacetA` and `FacetB` - it is valid Solidity - and both facets can emit.
3. Declare the events in an interface such as `IFacetEvents`, inherited from both `FacetA` and `FacetB` - it is valid in solidity. Both facets can now call `emit IFacetEvents.SomeEvent(...)`.

## Problem with 1:
Most hardhat typescript tooling won't allow to unit test this - because neither `FacetA` or `FacetB` explicitely declare `SomeEvent`, and so no types are consolidated knowing about that event.

## Problem with 2:
Using `hardhat-diamond-abi`, the project won't compile because `SomeEvent` is found as a duplicate between `FacetA` and `FacetB` when trying to build the ABI of their union for the diamond - although it's valid Solidity code.

## Problem with 3:
Although both facets inherit from the common interface `IFacetEvents`, there are no function signature overlap - so it should be fine. Yet, the project won't compile for the same reason as case 2 - `hardhat-diamond-abi` will complain that `IFacetEvents` is duplicated.

**Comment by phated** [comment]
Problem 1: We don't plan to deal with this. It's recommended by most Diamond documentation that you use libraries with internal functions to share code, so the events will be copied into the Facet ABIs.

Problem 2: That's by design, you are supposed to use the `filter` option to decide which things to allow (or duplicates to remove) in your ABI. See how [Dark Forest does it](https://github.com/darkforest-eth/eth/blob/master/hardhat.config.ts#L192-L195)

Problem 3: Use filter, as above.

As this library specifically opts for `strict: true` as the default to warn users about potential duplicate problems, and provides the `filter` option for people to remove duplicates, I don't think there is anything to do here.
